from enum import Enum


class ErrorCode(str, Enum):

    INVALID_FILE = "INVALID_FILE"
    INVALID_FILE_TYPE = "INVALID_FILE_TYPE"
    FILE_NAME_MISSING = "FILE_NAME_MISSING"
    FILE_EXTENSION_MISSING = "FILE_EXTENSION_MISSING"

    DOCUMENT_NOT_FOUND = "DOCUMENT_NOT_FOUND"
    DOCUMENT_PROCESSING = "DOCUMENT_PROCESSING"
    DOCUMENT_PROCESSING_FAILED = "DOCUMENT_PROCESSING_FAILED"
